# REPO: https://github.com/batchor/shadowrocket-config

[Rule]
# 自建规则集：命中则走代理
RULE-SET,https://raw.githubusercontent.com/batchor/shadowrocket-config/main/anthropic.list,PROXY
RULE-SET,https://raw.githubusercontent.com/batchor/shadowrocket-config/main/github.list,PROXY
RULE-SET,https://raw.githubusercontent.com/batchor/shadowrocket-config/main/wiki.banned.in.china.list,PROXY

# 其余所有流量一律直连
FINAL,DIRECT
